{ "1":[{"markup": ["danderson,dmandelin"], "type": "Highlight"},
       {"markup": ["Without exact type information, the compiler",
                   "must emit slower generalized machine code that can deal with all",
                   "potential type combinations. While compile-time static type infer-"], "type": "Highlight"},
       {"markup": ["Permission to make digital or hard copies of all or part of this work for personal or",
                   "classroom use is granted without fee provided that copies"], "type": "Highlight"}],
  "2":[{"markup": ["These techniques allow a VM to dynamically translate a pro-",
                   "gram to nested, type-specialized trace trees. "], 
        "content": "Underline note.", "type": "Underline"}],
  "3":[{"markup": ["load k from the trace activation "], "type": "Highlight"}],
  "10":[{"markup": ["Fraction of dynamic bytecodes executed by inter-",
                    "preter and on native traces"],
         "content": "Highlight content", "type": "Highlight"}],
  "12":[{"markup": ["controlﬂow-recursive"], "type": "Highlight"}],
  "13":[{"markup": ["controlﬂow-recursive"], "type": "Highlight"},
        {"content": "A simple note.", "type": "Text"}],
  "14":[{"markup": ["YETI: A graduallY",
                    "Extensible Trace Interpreter"], "type": "Underline"},
        {"markup": ["YETI: A graduallY",
                    "Extensible Trace Interpreter"], "type": "Highlight"}]
}