    <em:localized>
      <Description>
        <em:locale>ar</em:locale>
        <em:name>عارض PDF</em:name>
        <em:description>يستخدم HTML5 لعرض ملفات PDF مباشره من خلال Firefox.</em:description>
      </Description>
    </em:localized>
    <em:localized>
      <Description>
        <em:locale>bn-BD</em:locale>
        <em:name>পিডিএফ ভিউয়ার</em:name>
        <em:description>ফায়ারফক্স এ সরাসরি পিডিএফ দেখানোর জন্যে HTML5 ব্যাবহার করে।</em:description>
      </Description>
    </em:localized>
    <em:localized>
      <Description>
        <em:locale>ca</em:locale>
        <em:name>Visor d'arxius PDF</em:name>
        <em:description>HTML5 per veure documents</em:description>
      </Description>
    </em:localized>
    <em:localized>
      <Description>
        <em:locale>cs</em:locale>
        <em:name>PDF Viewer</em:name>
        <em:description>Používá HTML5 pro zobrazení PDF souborů přímo ve Firefoxu.</em:description>
      </Description>
    </em:localized>
    <em:localized>
      <Description>
        <em:locale>cy</em:locale>
        <em:name>PDF Viewer</em:name>
        <em:description>Yn defnyddio HTML5 i arddangos ffeiliau PDF yn uniongyrchol yn Firefox.</em:description>
      </Description>
    </em:localized>
    <em:localized>
      <Description>
        <em:locale>da</em:locale>
        <em:name>PDF Viewer</em:name>
        <em:description>Benytter HTML5 til at vise PDF-filer direkte i Firefox.</em:description>
      </Description>
    </em:localized>
    <em:localized>
      <Description>
        <em:locale>de</em:locale>
        <em:name>PDF Viewer</em:name>
        <em:description>Nutzt HTML5, um PDFs direkt in Firefox anzuzeigen.</em:description>
      </Description>
    </em:localized>
    <em:localized>
      <Description>
        <em:locale>el</em:locale>
        <em:name>Πρόγραμμα ανάγνωσης PDF</em:name>
        <em:description>Χρήση HTML5 για εμφάνιση αρχείων PDF κατευθείαν μέσα στο Firefox.</em:description>
      </Description>
    </em:localized>
    <em:localized>
      <Description>
        <em:locale>en-US</em:locale>
        <em:name>PDF Viewer</em:name>
        <em:description>Uses HTML5 to display PDF files directly in Firefox.</em:description>
      </Description>
    </em:localized>
    <em:localized>
      <Description>
        <em:locale>fa</em:locale>
        <em:name>نمایش‌دهندهٔ پی‌دی‌اف</em:name>
        <em:description>از اچ‌تی‌ام‌ال۵ برای نمایش پرونده‌های پی‌دی‌اف به‌صورت مستقیم در فایرفاکس استفاده می‌کند.</em:description>
      </Description>
    </em:localized>
    <em:localized>
      <Description>
        <em:locale>fi</em:locale>
        <em:name>PDF Lukuohjelma</em:name>
        <em:description>Näyttää PDF tiedostot suoraan Firefox:ssa HTML5:n avulla.</em:description>
      </Description>
    </em:localized>
    <em:localized>
      <Description>
        <em:locale>fr</em:locale>
        <em:name>PDF Viewer</em:name>
        <em:description>Utilise HTML5 pour afficher les documents PDF directement dans Firefox.</em:description>
      </Description>
    </em:localized>
    <em:localized>
      <Description>
        <em:locale>he</em:locale>
        <em:name>קורא PDF</em:name>
        <em:description>הצגת קבצי PDF ישירות ב־Firefox באמצעות HTML5.</em:description>
      </Description>
    </em:localized>
    <em:localized>
      <Description>
        <em:locale>it</em:locale>
        <em:name>PDF Viewer</em:name>
        <em:description>Usa HTML5 per visualizzare i file PDF direttamente in Firefox.</em:description>
      </Description>
    </em:localized>
    <em:localized>
      <Description>
        <em:locale>ja</em:locale>
        <em:name>PDF Viewer</em:name>
        <em:description>HTML5を使用して、Firefoxで直接PDFファイルを表示します。</em:description>
      </Description>
    </em:localized>
    <em:localized>
      <Description>
        <em:locale>ko</em:locale>
        <em:name>PDF 뷰어</em:name>
        <em:description>Firefox가 PDF 파일을 HTML5를 이용하여 직접 보여줍니다.</em:description>
      </Description>
    </em:localized>
    <em:localized>
      <Description>
        <em:locale>lt</em:locale>
        <em:name>PDF peržiūros programa</em:name>
        <em:description>PDF bylos vaizduojamos tiesiogiai, naudojant HTML5 Firefox naršyklėje.</em:description>
      </Description>
    </em:localized>
    <em:localized>
      <Description>
        <em:locale>nl</em:locale>
        <em:name>PDF-viewer</em:name>
        <em:description>Gebruikt HTML5 om PDF-bestanden direct in Firefox te openen.</em:description>
      </Description>
    </em:localized>
    <em:localized>
      <Description>
        <em:locale>pl</em:locale>
        <em:name>Przeglądarka PDF</em:name>
        <em:description>Używa HTML5 do wyświetlania plików PDF bezpośrednio w Firefoksie.</em:description>
      </Description>
    </em:localized>
    <em:localized>
      <Description>
        <em:locale>pt-BR</em:locale>
        <em:name>PDF Viewer</em:name>
        <em:description>Aprensenta PDFs no browser usando a tecnologia HTML5.</em:description>
      </Description>
    </em:localized>
    <em:localized>
      <Description>
        <em:locale>ro</em:locale>
        <em:name>Cititor PDF</em:name>
        <em:description>Afișează fișierele PDF direct în Firefox.</em:description>
      </Description>
    </em:localized>
    <em:localized>
      <Description>
        <em:locale>ru</em:locale>
        <em:name>PDF Viewer</em:name>
        <em:description>Показывает файлы PDF непосредственно в Firefox используя HTML5.</em:description>
      </Description>
    </em:localized>
    <em:localized>
      <Description>
        <em:locale>sr</em:locale>
        <em:name>ПДФ читач</em:name>
        <em:description>Користи ХТМЛ5 да би приказао ПДФ датотеке директно у Фајерфоксу.</em:description>
      </Description>
    </em:localized>
    <em:localized>
      <Description>
        <em:locale>sv</em:locale>
        <em:name>PDF-läsare</em:name>
        <em:description>Använder HTML5 för att visa PDF-filer direkt i Firefox.</em:description>
      </Description>
    </em:localized>
    <em:localized>
      <Description>
        <em:locale>tr</em:locale>
        <em:name>PDF Gösterici</em:name>
        <em:description>Firefox içerisinde PDFleri göstermek için HTML5 kullanır.</em:description>
      </Description>
    </em:localized>
    <em:localized>
      <Description>
        <em:locale>vi-VN</em:locale>
        <em:name>Trình Xem PDF</em:name>
        <em:description>Dùng HTML5 để hiện thị PDF trực tiếp trên FireFox.</em:description>
      </Description>
    </em:localized>
    <em:localized>
      <Description>
        <em:locale>zh-CN</em:locale>
        <em:name>PDF 查看器</em:name>
        <em:description>使用 HTML5 来支持在 Firefox 中直接显示 PDF 文件。</em:description>
      </Description>
    </em:localized>
    <em:localized>
      <Description>
        <em:locale>zh-TW</em:locale>
        <em:name>PDF 瀏覽器</em:name>
        <em:description>利用 HTML5 技術在 Firefox 中直接顯示 PDF 格式檔案。</em:description>
      </Description>
    </em:localized>
