PROG=java -Xms512m -Xmx1024m -jar ../../external/jsTestDriver/JsTestDriver-1.3.3d.jar --reset --port 4224 --browser firefox --tests all --testOutput ./test_reports/

test:
	$(PROG) ; \

.phony:: test

