name: CI
on: [push, pull_request]
permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    environment: code-coverage

    strategy:
      fail-fast: false
      matrix:
        node-version: [22, 24, 26]

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Restore cached PDF files
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: test/pdfs/*.pdf
          key: cached-pdf-files-${{ hashFiles('test/pdfs/*.pdf') }}
          restore-keys: |
            cached-pdf-files-
          enableCrossOsArchive: true

      - name: Run external tests
        run: npx gulp externaltest

      - name: Run CLI unit tests with code coverage
        run: npx gulp unittestcli --coverage --coverage-output build/coverage/unitcli

      - name: Save cached PDF files
        uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: test/pdfs/*.pdf
          key: cached-pdf-files-${{ hashFiles('test/pdfs/*.pdf') }}
          enableCrossOsArchive: true

      - name: Upload results to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: ./build/coverage/unitcli/lcov.info
          flags: unittestcli
          name: codecov-umbrella
          disable_search: true
          disable_telem: true
          verbose: true
