name: Lint Fluent Reference Files
on:
  push:
    paths:
      - 'l10n/en-US/**.ftl'
      - '.github/fluent_linter_config.yml'
      - '.github/workflows/fluent_linter.yml'
    branches:
      - master
  pull_request:
    paths:
      - 'l10n/en-US/**.ftl'
      - '.github/fluent_linter_config.yml'
      - '.github/workflows/fluent_linter.yml'
    branches:
      - master
  workflow_dispatch:
permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Use Python 3.14
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: '3.14'
          cache: 'pip'

      - name: Install Fluent dependencies
        run: |
          pip install -r .github/requirements.txt

      - name: Lint Fluent reference files
        run: |
          moz-fluent-lint ./l10n/en-US --config .github/fluent_linter_config.yml
