name: Lint Fluent Reference Files
on:
  push:
    paths:
      - 'l10n/en-US/**.ftl'
      - '.github/fluent_linter_config.yml'
      - '.github/workflows/fluent_linter.yml'
    branches:
      - master
  pull_request:
    paths:
      - 'l10n/en-US/**.ftl'
      - '.github/fluent_linter_config.yml'
      - '.github/workflows/fluent_linter.yml'
    branches:
      - master
  workflow_dispatch:
permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Use Python 3.14
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: '3.14'
          cache: 'pip'
          cache-dependency-path: '.github/fluent_linter_requirements.txt'

      - name: Install requirements
        run: pip install -r .github/fluent_linter_requirements.txt

      - name: Lint Fluent reference files
        run: moz-fluent-lint ./l10n/en-US --config .github/fluent_linter_config.yml
